server:
  error:
    include-message: always
  port: 8082

management:
  server:
    port: 9082

logging:
  level:
    root: info
  file:
    name: payments-ms-app.log

spring:
  application:
    name: payments-microservice

  profiles:
    active: USER,BATCH

  config:
    import: optional:file:.env[.properties]

  datasource:
    url: jdbc:postgresql://${DATASOURCE_URL}/${DATASOURCE_DATABASE}
    username: ${DATASOURCE_USER}
    password: ${DATASOURCE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: ${SHOW_SQL:false}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

  cache:
    type: caffeine
    cache-names: contextCache
    caffeine:
      spec: maximumSize=50_000,expireAfterWrite=30m,expireAfterAccess=5m

#  kafka:
#    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVER:localhost:9092}

  data:
    mongodb:
      host: ${MONGODB_HOST:localhost}
      port: ${MONGODB_PORT:27017}
      database: ${MONGODB_DATABASE:payments}

remote-cqrs:
  http:
    remote-modules[0]:
      module-name: context-auth
      url: ${CONTEXT_AUTH_HOST:http://localhost:8081}/api/cqrs
    remote-modules[1]:
      module-name: accounts
      url: ${ACCOUNTS_HOST:http://localhost:8083}/api/cqrs

pg:
  imports:
    enabled: true
    auto-start-importing-enabled: true

  kafka:
    bootstrap-server: ${KAFKA_BOOTSTRAP_SERVER:localhost:9092}

  lib:
    awsfiles:
      enabled: true
      bucket-name: ${AWS_BUCKET_NAME:payments-imported-files}
      access-key: ${AWS_ACCESS_KEY:}
      secret-key: ${AWS_SECRET_KEY:}
      aws-url: ${AWS_URL:}