SHOW_SQL: true
AWS_ACCESS_KEY: key
AWS_SECRET_KEY: secret
AWS_URL: localhost:12000

spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

  sql:
    init:
      mode: embedded